"""Initial migration

Revision ID: 0518da58b8c2
Revises: 
Create Date: 2026-08-25 06:44:12.977212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0518da58b8c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('direction', sa.String(length=10), nullable=False))
    op.add_column('sources', sa.Column('type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'type')
    op.drop_column('messages', 'direction')
    # ### end Alembic commands ###
